import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/mongodb';
import RegistrationCode from '@/models/RegistrationCode';

/**
 * Cron job untuk auto-generate registration code setiap hari
 * 
 * Untuk Vercel: Set up di Vercel Dashboard → Settings → Cron Jobs
 * Schedule: 0 0 * * * (setiap hari jam 00:00 UTC)
 * 
 * Untuk development lokal: Bisa dipanggil manual atau menggunakan cron service
 */
export async function GET(request) {
  try {
    // Verifikasi bahwa request berasal dari cron job (opsional, untuk security)
    const authHeader = request.headers.get('authorization');
    const cronSecret = process.env.CRON_SECRET;
    
    // Jika CRON_SECRET di-set, verifikasi request
    if (cronSecret && authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json(
        { message: 'Unauthorized' },
        { status: 401 }
      );
    }
    
    await connectToDatabase();
    
    // Cek apakah ada kode aktif yang masih valid
    const activeCode = await RegistrationCode.getActiveCode();
    const now = new Date();
    
    // Jika ada kode aktif dan belum expire, tidak perlu generate baru
    if (activeCode && new Date(activeCode.expiresAt) > now) {
      const timeRemaining = new Date(activeCode.expiresAt) - now;
      const hoursRemaining = Math.floor(timeRemaining / (1000 * 60 * 60));
      
      return NextResponse.json({
        message: 'Kode registrasi masih aktif',
        code: activeCode.code,
        hoursRemaining,
        skipped: true,
      });
    }
    
    // Nonaktifkan semua kode lama yang masih aktif
    await RegistrationCode.updateMany(
      { isActive: true },
      { isActive: false }
    );
    
    // Generate kode baru (6 digit angka)
    const newCode = RegistrationCode.generateNewCode();
    
    // Set expire 24 jam dari sekarang
    const expiresAt = new Date();
    expiresAt.setHours(expiresAt.getHours() + 24);
    
    // Buat kode baru
    const registrationCode = await RegistrationCode.create({
      code: newCode,
      expiresAt: expiresAt,
      isActive: true,
      generatedBy: null, // System generated
    });
    
    console.log(`✅ Auto-generated registration code: ${newCode}, expires at: ${expiresAt}`);
    
    return NextResponse.json({
      message: 'Kode registrasi berhasil di-generate secara otomatis',
      code: registrationCode.code,
      expiresAt: registrationCode.expiresAt,
      autoGenerated: true,
    });
  } catch (error) {
    console.error('Error in cron job for generating registration code:', error);
    return NextResponse.json(
      { message: 'Error generating registration code', error: error.message },
      { status: 500 }
    );
  }
}

